# config.yaml

# Configuration version (for schema validation)
version: 1.0

# Device selection
device: cuda:0

# Paths to datasets
data:
  train_path: /fast_storage/hyeokgi/data_v2_slice_512/train
  val_path:   /home/intern2/data_v2_slice_512/valid


# Model specification
model:
  params:
    device: cuda:0


# loss function
loss:
  type: "mse_loss"
  params: {}

# Optimizer settings
optimizer:
  type: Adam
  params:
    lr:           0.0001
    weight_decay: 0.0001

# Learning‐rate scheduler (optional)
scheduler:
  type: StepLR
  params:
    step_size: 25
    gamma: 0.5 

# Training parameters
training:
  resume:                     true
  epochs:                     500
  batch_size:                 4
  num_workers:                1
  early_stopping_patience:    100
  parallel:                   true # use multiple GPUs if available

# Logging & checkpointing
logging:
  log_dir:        ./var/logs
  checkpoint_dir: ./var/checkpoints
  sample_dir:     ./var/samples
  sample_interval: 10          # save samples every 1 epochs
  checkpoint_save_interval: 5
  level:          INFO
  log_interval:   100
  structured:     true      # emit JSON‐formatted logs
  format:         json

# Metrics to compute and track
metrics:
  report:       [accuracy, precision, recall]
  save_history: true

# Hyperparameter sweep definitions
# sweep:
#   optimizer.params.lr:       0.0005
#   training.batch_size:       32

